---
deployment:
  tasks:
    #- export $(grep -v '^#' .env | xargs) #Set environment variables
    - set -a # automatically export all variables
    - source .env
    - set +a
    - /bin/cp -R scripts $DEPLOY_PATH #Deploy scripts directory
    - /bin/cp -R style $DEPLOY_PATH #Deploy style directory
    - /bin/cp index.html $DEPLOY_PATH #Deploy index.html file
