---
deployment:
  tasks:
    - export DEPLOY_PATH=/home2/charcount/public_html/ #Set deploy path
    - /bin/cp -R scripts $DEPLOY_PATH #Deploy scripts directory
    - /bin/cp -R style $DEPLOY_PATH #Deploy style directory
    - /bin/cp index.html $DEPLOY_PATH #Deploy index.html file
